# <center> BIGDATA X YONSEI CAMPUS </center>
### <center> 키워드 분석 및 문서 분석 </center>
#### <center> 키워드 분석: 키워드 오탈자교정 </center>
---------------------------
#### <div style="text-align: right"> 손근영 </div>

## 1. Keyword Analysis - 키워드 오탈자교정
### Motivation
* 검색의도가 분명한 사용자 조차 제대로된 키워드를 입력하는 것은 어려운 일
* 스마트폰에서는 더욱 더 오타가 많이 입력됨
* 교정 서비스가 발달할 수록 사용자는 더욱 더 오타를 정정하지 않음
 * 예를들면 구글에서 영어 단어 철자가 기억이 안나도 소리나는 대로 검색
* 검색 포탈에서는 '넹이버', '당므'와 같은 검색어가 매일 탑 100위권안에 진입
 * 하찮은 검색어보다 훨씬 더 많은 pv를 보유하고 있음

## 1. Keyword Analysis - 키워드 오탈자교정
### Key Idea
* 사용자는 오타를 우선 입력 한 뒤, 결과가 나쁘면 다시 교정 검색을 시도
* 포털이 오타를 정정해주지 못하는 경험을 하면, 오타 입력 중 다시 정타로 스스로 고침
* 포털이 오타를 정정해주는 경험을 하면, 우선 입력한 뒤 상황을 선택
* 로그에서의 상황
 * 어떤 사용자의 이전 키워드와 이후 키워드가 아주 유사하다면 사용자가 오타를 정정한 것 아닐까?
 * 이전 키워드와 이후 키워드의 등장확률이 이후 키워드가 훨씬더 높다면 이후 키워드가 정타 아닐까?

## 2. 키워드 오탈자교정의 서비스 화면
<center><img src='img/06_01.png' height=100% width=100%></center>

## 3. 오탈자 교정의 가치
* 기존의 키워드 컴포넌트보다 중요한 역할
 * 사용자의 입력과 결과에 직접적 관여를 함
  * 기존의 키워드는 찾을 것을 모르는 사용자에게 무언가 제안해 주는 형태
  * 오타 교정은 사용자의 입력을 더 잘나오게 보정해주는 역할 (오타를 입력하는 사용자는 결과화면을 못볼 수 있음)
* 구글의 경우 오타교정에 아주 많은 노력을 기울임
* 사용자가 어떤 엉터리입력을 치던 의도를 파악하여 가치있는 검색어로 변경
 * 검색 품질을 높여주는 효과
 * 사용자는 대충 쳐도, 영어단어를 몰라도 의도를 파악해서 잘 찾아주는 검색엔진에 머무르고 싶어함

## 3. 오탈자 교정 가치

* 검색양이 증가하면?
 * PV 상승 / 이용자의 의도가 더욱 더 log안에 저장됨 
 * 오타가 더욱 발생
  * 더욱 더 다양한 오타를 가질 수 있게 됨
--------------------------------------
* 더욱 더 다양한 오타를 가지게 되면?
 * 사용자들은 더욱 더 아무렇게나 어려운 오타를 치면서 풍부한 결과를 획득함
 * 어려운 오타들이 쌓이면 사용자는 결과적으로 해당 포탈에 lock-in됨

## 4. 오탈자 유형

### Qwerty형
 * 한글 자판의 입력을 그대로 영문 입력으로 오타를 내는 유형
  * spdlqj -> 네이버
  
### Qwert2형
 * 한글 자판의 입력을 대부분 맞게 입력하였지만 중간 영타에서 오타를 내는 유형
  * 갤럭시note2 -> 갤럭시ㅜㅐㅅㄷ2
  
### 순수오타형
 * 삽입 오류
  * 넹이버 (불필요한 ㅇ이 삽입됨)
 * 치환 오류
  * 네ㅣㅇ버 (ㅣ와ㅇ의 순서가 치환됨)
 * 식제 오류
  * 넹버(ㅣ를 삭체함)
 * 띄어쓰기 오류
  * 넹 ㅣ버 (ㅇ과ㅣ 가이에 공백이 추가됨)
 * 단어 모름 오류
  * 내이버
  
### 복합형
 * 순수 오타형의 타양한 케이스와 Qwerty형이 복합적으로 섞인 경우
  * 배트남 여ㅐㅎㅇ 해해해! -> 아마도 "베트남 여행 gogogo!"

## 5. 오타, 정타 등장 확률

* 오타와 정타가 Pair로 추출되었다고 가정 (연관 검색어 pair와 같이)
 * 총 검색어 log의 word count에서 다음 공식이 성립할 확률이 대단히 높음
 
 $$ P(오타) < P(정타) \nonumber $$
 
 * 등장하기 어려운 오타일 수록 쉬운 오타 대비 확률이 낮아진다고 가정 할 수 있음
 
 * P(sp이ㅂㅓ) < P(넹이버) < P(네이버)

## 6. 편집 거리 (levenshtein edit distance)
* 문제 정의
 * 주어진 2개의 문자열 (오타, 정타 후보 pair)이 몇번의 글자 수정을 통하면 통일한 문자열이 될까?
 * 그 최소 횟수를 구하는 문제
 
<center><img src='img/06_02.png' height=100% width=100%></center>

## 6. 편집 거리 (levenshtein edit distance)

### 편집거리와 오타의 연관성
* 사용자는 입력의 1,2글자 정도가 오타이며, '실수'로 입력함
* 가정
 * 오타와 정타의 편집거리는 2내외 일것
 * 오타 공식: editdistnace(오타, 정타) <= 2

## 7. Qwerty 오타 치환

* 영한 전환 오타를 일반화
 * 한글은 영타 자판과 1:1 매핑하지 않음
 * 그러나 자소는 영타 자판과 1:1 매핑함
  * jaso(한글) = ㅎㅏㄴㄱㅡㄹ
  * Qwerty(ㅎㅏㄴㄱㅡㄹ) = gksrmf
 ---------------------------------
* qwerty 오타 공식
 * 정타 != 오타 and qwerty(jaso(정타)) == qwerty(jaso(오타))
 * True이면 qwerty 전환 오타

In [1]:
#해당 함수는 이전대비 된소리에 대한 처리가 포함되어있음
#모든 한글에 대한 처리를 하기 위함
def decomposeKStr(kstr):
    def decomposeKChar(ch):
        if not(0xAC00 <= ord(ch) <= 0xD7AF):
            return ch

        cho  = ["ㄱ", "ㄲ", "ㄴ", "ㄷ", "ㄸ", "ㄹ", "ㅁ", "ㅂ", "ㅃ", "ㅅ", "ㅆ", "ㅇ", "ㅈ", "ㅉ", "ㅊ", "ㅋ", "ㅌ", "ㅍ", "ㅎ" ]
        jung = ["ㅏ", "ㅐ", "ㅑ", "ㅒ", "ㅓ", "ㅔ", "ㅕ", "ㅖ", "ㅗ", "ㅘ", "ㅙ", "ㅚ", "ㅛ", "ㅜ", "ㅝ", "ㅞ", "ㅟ", "ㅠ", "ㅡ", "ㅢ", "ㅣ"]
        jung_double = {"ㅘ":"ㅗㅏ", "ㅙ":"ㅗㅐ", "ㅚ":"ㅗㅣ", "ㅝ":"ㅜㅓ", "ㅞ":"ㅜㅔ", "ㅟ":"ㅜㅣ", "ㅢ":"ㅡㅣ"}
        jong = ["", "ㄱ", "ㄲ", "ㄳ", "ㄴ", "ㄵ", "ㄶ", "ㄷ", "ㄹ", "ㄺ", "ㄻ", "ㄼ", "ㄽ", "ㄾ", "ㄿ", "ㅀ", "ㅁ", "ㅂ", "ㅄ", "ㅅ", "ㅆ", "ㅇ", "ㅈ", "ㅊ", "ㅋ", "ㅌ", "ㅍ", "ㅎ"]
        jong_double = {"ㄳ":"ㄱㅅ", "ㄵ":"ㄴㅈ", "ㄶ":"ㄴㅎ", "ㄺ":"ㄹㄱ", "ㄻ":"ㄹㅁ", "ㄼ":"ㄹㅂ", "ㄽ":"ㄹㅅ",
                       "ㄾ":"ㄹㅌ", "ㄿ":"ㄹㅍ", "ㅀ":"ㄹㅎ", "ㅄ":"ㅂㅅ"
                      }

        n = ord(ch) - 0xAC00

        last = n % 28
        middle = ((n-last) // 28) % 21
        first = (((n-last) // 28) - middle) // 21
        return cho[first], jung_double.get(jung[middle], jung[middle]), jong_double.get(jong[last], jong[last])
    
    res = []
    for ch in kstr:
        res += decomposeKChar(ch)
    return "".join(res)

In [2]:
#jaso -> qwerty 전환 함수
def qweryKStr(kstr):
    qwerty = "qwertyuiopasdfghjklzxcvbnmQWERTOP"
    jaso = "ㅂㅈㄷㄱㅅㅛㅕㅑㅐㅔㅁㄴㅇㄹㅎㅗㅓㅏㅣㅋㅌㅊㅍㅠㅜㅡㅃㅉㄸㄲㅆㅒㅖ"
    
    table = {j:q for j,q in zip(jaso, qwerty)}
    return "".join(table.get(ch, ch) for ch in decomposeKStr(kstr))

In [3]:
print(qweryKStr("네이버"))
print(qweryKStr("spdlqj"))

spdlqj
spdlqj

In [4]:
#edit distance 함수
import numpy as np
def levenshtein(seq1, seq2):  
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in range(size_x):
        matrix [x, 0] = x
    for y in range(size_y):
        matrix [0, y] = y

    for x in range(1, size_x):
        for y in range(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    return int(matrix[size_x - 1, size_y - 1])

In [5]:
print(levenshtein("네이버", "네이버"))
print(levenshtein("넹이버", "네이버"))
print(levenshtein("다음", "네이버"))

0
1
3

## 8. pandas를 활용한 오타교정 (사전형)
- 연관검색어 로직을 이용하여 느슨한 연관 검색어 집합을 생성

In [8]:
#이전 사용했던 연관 검색어를 추출하는 로직을 그대로 사용함
#df7까지 수행하면 A, B, key_A, key_B를 가지는 df가 나옴
import pandas as pd
import csv 
df = pd.read_csv('data/sample_search_log.txt', sep='\t', header=None, names = ['date', 'id', 'keyword', 'result'],
                 quoting=csv.QUOTE_NONE)
df =  df[df["date"].map(str).map(len) == 15]
df['date'] = df.date.apply(lambda x: pd.datetime.strptime(x, '%Y%m%d-%H%M%S'))
df = df[['date', 'id', 'keyword']]
df = df.dropna()
df = df.sort_values(by=['date', 'id'])
gdf = df.groupby('id').filter(lambda x:x['keyword'].count() > 2).groupby('id')
df2 = gdf.agg({'keyword':list})
df3 = df2.keyword.apply(lambda x:[tuple(x[i:i+2]) for i in range(len(x)-1)]).to_frame()
df4 = df3.keyword.apply(pd.Series)
df5 = df4.stack().to_frame('pairwise')
df6 = df5.reset_index(level=0)
df7 = df6.pairwise.apply(lambda x:x[0]).to_frame('A')
df7['B'] = df6.pairwise.apply(lambda x:x[1])
df7['key_A'] = df7.A.apply(lambda x:x.replace(' ','').lower())
df7['key_B'] = df7.B.apply(lambda x:x.replace(' ','').lower())
df7.head(10)

                A           B          key_A      key_B
0         다이어트 효과  미료 카리스마 사진         다이어트효과   미료카리스마사진
1      미료 카리스마 사진     2주 20kg       미료카리스마사진     2주20kg
2         2주 20kg   하루 1시간 걷기         2주20kg    하루1시간걷기
0             엘소드         이어폰            엘소드        이어폰
1             이어폰  광개토태왕 미리보기            이어폰  광개토태왕미리보기
0            가수박모    박혜경 공식입장           가수박모    박혜경공식입장
1        박혜경 공식입장         임수향        박혜경공식입장        임수향
0  bubble trouble    테트리스 한게임  bubbletrouble    테트리스한게임
1        테트리스 한게임     타이젬 외톨이        테트리스한게임     타이젬외톨이
2         타이젬 외톨이     Dollars         타이젬외톨이    dollars

In [9]:
#qwerty를 수행시켜 각 key_A, key_B에 대해서 qwerty화 시킨다
df7_copy = df7.copy()
df7_copy['qwert_A'] = df7_copy.key_A.map(qweryKStr)
df7_copy['qwert_B'] = df7_copy.key_B.map(qweryKStr)
df7_copy.head(10)

,A,B,key_A,key_B,qwert_A,qwert_B
0,다이어트 효과,미료 카리스마 사진,다이어트효과,미료카리스마사진,ekdldjxmgyrhk,alfyzkfltmaktkwls
1,미료 카리스마 사진,2주 20kg,미료카리스마사진,2주20kg,alfyzkfltmaktkwls,2wn20kg
2,2주 20kg,하루 1시간 걷기,2주20kg,하루1시간걷기,2wn20kg,gkfn1tlrksrjerl
0,엘소드,이어폰,엘소드,이어폰,dpfthem,dldjvhs
1,이어폰,광개토태왕 미리보기,이어폰,광개토태왕미리보기,dldjvhs,rhkdroxhxodhkdalflqhrl
0,가수박모,박혜경 공식입장,가수박모,박혜경공식입장,rktnqkrah,qkrgPrudrhdtlrdlqwkd
1,박혜경 공식입장,임수향,박혜경공식입장,임수향,qkrgPrudrhdtlrdlqwkd,dlatngid
0,bubble trouble,테트리스 한게임,bubbletrouble,테트리스한게임,bubbletrouble,xpxmfltmgksrpdla
1,테트리스 한게임,타이젬 외톨이,테트리스한게임,타이젬외톨이,xpxmfltmgksrpdla,xkdlwpadhlxhfdl
2,타이젬 외톨이,Dollars,타이젬외톨이,dollars,xkdlwpadhlxhfdl,dollars

In [10]:
# qwerty_A와 qwerty_B에 edit distance 동작을 수행한다
df8 = df7_copy[(df7_copy.qwert_A.str.len() < 20) & (df7_copy.qwert_B.str.len() < 20)]
df8['qwert_ed'] = df8[['qwert_A', 'qwert_B']].apply(lambda x:levenshtein(*x), axis=1)
df8.head(10)

/Users/kakao/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,A,B,key_A,key_B,qwert_A,qwert_B,qwert_ed
0,다이어트 효과,미료 카리스마 사진,다이어트효과,미료카리스마사진,ekdldjxmgyrhk,alfyzkfltmaktkwls,15
1,미료 카리스마 사진,2주 20kg,미료카리스마사진,2주20kg,alfyzkfltmaktkwls,2wn20kg,16
2,2주 20kg,하루 1시간 걷기,2주20kg,하루1시간걷기,2wn20kg,gkfn1tlrksrjerl,13
0,엘소드,이어폰,엘소드,이어폰,dpfthem,dldjvhs,6
0,bubble trouble,테트리스 한게임,bubbletrouble,테트리스한게임,bubbletrouble,xpxmfltmgksrpdla,14
1,테트리스 한게임,타이젬 외톨이,테트리스한게임,타이젬외톨이,xpxmfltmgksrpdla,xkdlwpadhlxhfdl,13
2,타이젬 외톨이,Dollars,타이젬외톨이,dollars,xkdlwpadhlxhfdl,dollars,13
3,Dollars,Dollars 다라즈,dollars,dollars다라즈,dollars,dollarsekfkwm,6
0,낙뢰방지,계장,낙뢰방지,계장,skrfhlqkdwl,rPwkd,8
1,계장,제너배리어,계장,제너배리어,rPwkd,wpsjqofldj,9

In [11]:
# 러프한 오타 후보를 포함한 df 를 추출해본다
# ed < 충분히 큰 거리 & 오타와 정타 키워드가 같지 않은 필드
df9 = df8[(df8.qwert_ed < 6) & (df8.key_A != df8.key_B)]
df9.head(10)

,A,B,key_A,key_B,qwert_A,qwert_B,qwert_ed
0,레바,백묘,레바,백묘,fpqk,qoray,5
1,포항 모텔,포항시청,포항모텔,포항시청,vhgkdahxpf,vhgkdtlcjd,5
0,지너 항복,지너 항복 이탈,지너항복,지너항복이탈,wlsjgkdqhr,wlsjgkdqhrdlxkf,5
1,지너 항복 이탈,지너 항복,지너항복이탈,지너항복,wlsjgkdqhrdlxkf,wlsjgkdqhr,5
5,구의 쪽갈비,쪽갈비,구의쪽갈비,쪽갈비,rndmlWhrrkfql,Whrrkfql,5
7,박진희 화보,박진희 리즈,박진희화보,박진희리즈,qkrwlsgmlghkqh,qkrwlsgmlflwm,5
1,중동 우편번호,상남동 우편번호,중동우편번호,상남동우편번호,wndehddnvusqjsgh,tkdskaehddnvusqjsgh,5
5,남산동 우편번호,신촌동 우편번호,남산동우편번호,신촌동우편번호,skatksehddnvusqjsgh,tlschsehddnvusqjsgh,5
6,qq,바이두,qq,바이두,qq,qkdlen,5
1,대부업 조회,대부업체 조회,대부업조회,대부업체조회,eoqndjqwhghl,eoqndjqcpwhghl,2

In [12]:
# key_A 쪽 확률 P(key_A)를 구하기
gdf = df9.groupby(by='key_A')[['key_A']]
probA_df9 = gdf.count().rename(columns={'key_A':'cnt_A'}).sort_values(by='cnt_A', ascending=False)
probA_df9['prob_A'] = probA_df9.cnt_A/probA_df9.cnt_A.sum()
probA_df9.head(5)

       cnt_A    prob_A
key_A
정다연       93  0.006438
박봄        74  0.005123
안혜경       73  0.005053
이재진       59  0.004084
윤다경       59  0.004084

In [13]:
# key_B 쪽 확률 P(key_B)를 구하기
gdf = df9.groupby(by='key_B')[['key_B']]
probB_df9 = gdf.count().rename(columns={'key_B':'cnt_B'}).sort_values(by='cnt_B', ascending=False)
probB_df9['prob_B'] = probB_df9.cnt_B/probB_df9.cnt_B.sum()
probB_df9.head(5)

       cnt_B    prob_B
key_B
윤다경       82  0.005676
박봄        68  0.004707
안은정       55  0.003807
안혜경       46  0.003184
정다연       44  0.003046

In [14]:
# 각 확률 P(key_A) 와 P(key_B)를 조인한다
df10 = df9.join(probA_df9.prob_A, on='key_A', how='left').join(probB_df9.prob_B, on='key_B', how='left')
df10.head(5)

,A,B,key_A,key_B,qwert_A,qwert_B,qwert_ed,prob_A,prob_B
0,레바,백묘,레바,백묘,fpqk,qoray,5,0.000208,0.000069
1,포항 모텔,포항시청,포항모텔,포항시청,vhgkdahxpf,vhgkdtlcjd,5,0.000069,0.000069
0,지너 항복,지너 항복 이탈,지너항복,지너항복이탈,wlsjgkdqhr,wlsjgkdqhrdlxkf,5,0.000069,0.000069
1,지너 항복 이탈,지너 항복,지너항복이탈,지너항복,wlsjgkdqhrdlxkf,wlsjgkdqhr,5,0.000069,0.000069
5,구의 쪽갈비,쪽갈비,구의쪽갈비,쪽갈비,rndmlWhrrkfql,Whrrkfql,5,0.000069,0.000069

In [15]:
# 오타 일경우 P(key_A) < P(key_B)가 성립한다고 가정
# 수행한다
df11 = df10[df10.prob_A < df10.prob_B]
df11.head(10)

,A,B,key_A,key_B,qwert_A,qwert_B,qwert_ed,prob_A,prob_B
2,신수지 징계,신수지,신수지징계,신수지,tlstnwlwldrP,tlstnwl,5,0.001731,0.002077
1,안혜경,윤다경,안혜경,윤다경,dksgPrud,dbsekrud,3,0.005053,0.005676
3,지연,정다연,지연,정다연,wldus,wjdekdus,4,0.000623,0.003046
0,로질리,고걸,로질리,고걸,fhwlffl,rhrjf,5,0.000069,0.000138
1,수요일날씨,화요일날씨,수요일날씨,화요일날씨,tndydlfskfTl,ghkdydlfskfTl,3,0.000208,0.000900
0,구글,다음,구글,다음,rnrmf,ekdma,4,0.001038,0.002561
0,노바,소이,노바,소이,shqk,thdl,3,0.000069,0.002146
1,온유,니콜,온유,니콜,dhsdb,slzhf,5,0.000069,0.000208
2,이은주,이재진,이은주,이재진,dldmswn,dlwowls,5,0.001661,0.002492
1,유시민,이재진,유시민,이재진,dbtlals,dlwowls,4,0.001454,0.002492

In [16]:
# edit distance를 엄격하게 수행해본다 1 or 2
df12 = df11[df11.qwert_ed < 2]
df12.head(10)

,A,B,key_A,key_B,qwert_A,qwert_B,qwert_ed,prob_A,prob_B
1,kbs,sbs,kbs,sbs,kbs,sbs,1,0.000208,0.000277
2,LG전자 유상증ㅈ아,LG전자 유상증자,lg전자유상증ㅈ아,lg전자유상증자,lgwjswkdbtkdwmdwdk,lgwjswkdbtkdwmdwk,1,0.000069,0.000138
1,16회연금복권,17회연금복권,16회연금복권,17회연금복권,16ghldusrmaqhrrnjs,17ghldusrmaqhrrnjs,1,0.000346,0.000415
3,사마귀유치원 4회,사마귀유치원 5회,사마귀유치원4회,사마귀유치원5회,tkakrnldbcldnjs4ghl,tkakrnldbcldnjs5ghl,1,0.000069,0.000277
0,메이플인송,메이플인소야,메이플인송,메이플인소야,apdlvmfdlsthd,apdlvmfdlsthdi,1,0.000069,0.000138
0,삼성커드,삼성카드,삼성커드,삼성카드,tkatjdzjem,tkatjdzkem,1,0.000069,0.000277
0,재밋는게임,재밌는게임,재밋는게임,재밌는게임,woaltsmsrpdla,woalTsmsrpdla,1,0.000069,0.000138
2,11회연금복권,16회연금복권,11회연금복권,16회연금복권,11ghldusrmaqhrrnjs,16ghldusrmaqhrrnjs,1,0.000069,0.000346
89,옵티머스3ㅇ,옵티머스3d,옵티머스3ㅇ,옵티머스3d,dhqxlajtm3d,dhqxlajtm3d,0,0.000069,0.000138
2,오랜지,오렌지,오랜지,오렌지,dhfoswl,dhfpswl,1,0.000069,0.000138

In [17]:
# 명백한 오타를 구할 수 있음
# qwerty 는 서로 같지만 입력은 다른 경우
typo_type1 = df12[(df12.key_A != df12.key_B) & (df12.qwert_A == df12.qwert_B)].sort_values(by='prob_B', ascending=False)
typo_type1['type'] = '부분오타형'
typo_type1.head(10)

,A,B,key_A,key_B,qwert_A,qwert_B,qwert_ed,prob_A,prob_B,type
0,qkrqha,박봄,qkrqha,박봄,qkrqha,qkrqha,0,0.000069,0.004707,부분오타형
2,아이폰4ㄴ,아이폰4s,아이폰4ㄴ,아이폰4s,dkdlvhs4s,dkdlvhs4s,0,0.000069,0.000969,부분오타형
0,LGWJSWK,LG전자,lgwjswk,lg전자,lgwjswk,lgwjswk,0,0.000069,0.000346,부분오타형
3,옵티머스 qlr,옵티머스 빅,옵티머스qlr,옵티머스빅,dhqxlajtmqlr,dhqxlajtmqlr,0,0.000069,0.000277,부분오타형
0,dnteo,웃대,dnteo,웃대,dnteo,dnteo,0,0.000069,0.000208,부분오타형
89,옵티머스3ㅇ,옵티머스3d,옵티머스3ㅇ,옵티머스3d,dhqxlajtm3d,dhqxlajtm3d,0,0.000069,0.000138,부분오타형
0,ab,뮤,ab,뮤,ab,ab,0,0.000069,0.000138,부분오타형
2,ㅏ5,K5,ㅏ5,k5,k5,k5,0,0.000069,0.000138,부분오타형
0,ㅂㅗㄴ죽,본죽,ㅂㅗㄴ죽,본죽,qhswnr,qhswnr,0,0.000069,0.000138,부분오타형
0,xhavkdlf,톰파일,xhavkdlf,톰파일,xhavkdlf,xhavkdlf,0,0.000069,0.000138,부분오타형

In [18]:
# 명백한 오타를 구할 수 있음
# 사전 입력과 사전 qwerty 는 서로 같지만 사후 입력과 사후 qwert는 다른 경우
typo_type2 = df12[(df12.key_A == df12.qwert_A) & (df12.key_B != df12.qwert_B)].sort_values(by='prob_B', ascending=False)
typo_type2['type'] = '치환형'
typo_type2.head(10)

,A,B,key_A,key_B,qwert_A,qwert_B,qwert_ed,prob_A,prob_B,type
0,qkrqha,박봄,qkrqha,박봄,qkrqha,qkrqha,0,0.000069,0.004707,치환형
1,Tjsl,써니,tjsl,써니,tjsl,Tjsl,1,0.000069,0.000554,치환형
0,LGWJSWK,LG전자,lgwjswk,lg전자,lgwjswk,lgwjswk,0,0.000069,0.000346,치환형
2,dnfldmsgd,우리은행,dnfldmsgd,우리은행,dnfldmsgd,dnfldmsgod,1,0.000069,0.000277,치환형
0,dnteo,웃대,dnteo,웃대,dnteo,dnteo,0,0.000069,0.000208,치환형
0,ab,뮤,ab,뮤,ab,ab,0,0.000069,0.000138,치환형
0,xhavkdlf,톰파일,xhavkdlf,톰파일,xhavkdlf,xhavkdlf,0,0.000069,0.000138,치환형

In [19]:
# 사전 key 도 qwerty와 다르고 사후 key 도 qwerty와 다르면 명박하게 어려운 오타가 된다 
type_type3 = df12[(df12.key_A != df12.qwert_A) & (df12.key_B != df12.qwert_B)].sort_values(by='prob_B', ascending=False)
type_type3['type'] = '확률형'
type_type3.head(10)

,A,B,key_A,key_B,qwert_A,qwert_B,qwert_ed,prob_A,prob_B,type
1,윤다경\,윤다경,윤다경\,윤다경,dbsekrud\,dbsekrud,1,0.000069,0.005676,확률형
0,정다은,정다연,정다은,정다연,wjdekdms,wjdekdus,1,0.000069,0.003046,확률형
3,김두환,김두한,김두환,김두한,rlaenghks,rlaengks,1,0.000138,0.002561,확률형
1,그루ㅗㄴ,그루폰,그루ㅗㄴ,그루폰,rmfnhs,rmfnvhs,1,0.000069,0.001177,확률형
0,아이폰4,아이폰4s,아이폰4,아이폰4s,dkdlvhs4,dkdlvhs4s,1,0.000485,0.000969,확률형
2,아이폰4,아이폰4s,아이폰4,아이폰4s,dkdlvhs4,dkdlvhs4s,1,0.000485,0.000969,확률형
2,아이폰4ㄴ,아이폰4s,아이폰4ㄴ,아이폰4s,dkdlvhs4s,dkdlvhs4s,0,0.000069,0.000969,확률형
0,김ㅇ한,김요한,김ㅇ한,김요한,rladgks,rladygks,1,0.000069,0.000969,확률형
2,아이폰4,아이폰4s,아이폰4,아이폰4s,dkdlvhs4,dkdlvhs4s,1,0.000485,0.000969,확률형
3,아이폰4,아이폰4s,아이폰4,아이폰4s,dkdlvhs4,dkdlvhs4s,1,0.000485,0.000969,확률형

In [20]:
6# 오타의 유형을 union해서 통합된 결과로 만든다
res = pd.concat([typo_type1[['A', 'B', 'type']], typo_type2[['A', 'B', 'type']], type_type3[['A', 'B', 'type']] ])
res = res.set_index('A')
res.head(10)

               B   type
A
qkrqha        박봄  부분오타형
아이폰4ㄴ      아이폰4s  부분오타형
LGWJSWK     LG전자  부분오타형
옵티머스 qlr  옵티머스 빅  부분오타형
dnteo         웃대  부분오타형
옵티머스3ㅇ    옵티머스3d  부분오타형
ab             뮤  부분오타형
ㅏ5            K5  부분오타형
ㅂㅗㄴ죽          본죽  부분오타형
xhavkdlf     톰파일  부분오타형

In [21]:
# 테스트를 하기 위해서 메모리에 저장
res2= {key:val for key, val in zip(res.index, [(x, y) for x, y in zip(res.B, res.type)])}

In [22]:
from ipywidgets import widgets
from IPython.display import display
from IPython.display import clear_output
text = widgets.Text()

def handle_submint(sender):
    clear_output()
    display(text)
    print(get_typo(text.value))

#text.observe(handle_submint)
text.on_submit(handle_submint)

def get_typo(raw):
    return res2.get(raw.replace(' ', '').lower(), [])

In [23]:
display(text)

Text(value='qkrqha')

('박봄', '치환형')

## quiz 1
- 더욱 다양한 종류의 오타들이 있을지 생각해보자