# 데이터 전처리

In [21]:
import numpy as np
import pandas as pd

## LabelEncoder

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
df = pd.DataFrame({
    'pName':['냉장고','TV','에어컨','냉장고','노트북','공기청정기'],
    'price':[100,80,150,100,50,40]
})
df

   pName  price
0    냉장고    100
1     TV     80
2    에어컨    150
3    냉장고    100
4    노트북     50
5  공기청정기     40

In [24]:
le = LabelEncoder()
le.fit(df.pName) # 각 값들과 코드의 매핑 관계 생성
le.transform(df.pName)  # le.fit_transform(df.pName) 으로 하면 한번에 할 수 있다

array([2, 0, 4, 2, 3, 1])

In [25]:
df['pid'] = le.transform(df.pName)
df

   pName  price  pid
0    냉장고    100    2
1     TV     80    0
2    에어컨    150    4
3    냉장고    100    2
4    노트북     50    3
5  공기청정기     40    1

In [26]:
print('Encoding Class : ',le.classes_)

Encoding Class :  ['TV' '공기청정기' '냉장고' '노트북' '에어컨']

In [27]:
le.inverse_transform([3,1,2,3,2,0,1,2]) # 숫자를 클래스로

array(['노트북', '공기청정기', '냉장고', '노트북', '냉장고', 'TV', '공기청정기', '냉장고'],
      dtype=object)

## OneHotEncoder

In [28]:
from sklearn.preprocessing import OneHotEncoder

In [29]:
df = pd.DataFrame({
    'pName':['냉장고','TV','에어컨','냉장고','노트북','공기청정기'],
    'price':[100,80,150,100,50,40]
})
df

   pName  price
0    냉장고    100
1     TV     80
2    에어컨    150
3    냉장고    100
4    노트북     50
5  공기청정기     40

In [30]:
ohe = OneHotEncoder()
ohe.fit_transform(df.pName.values.reshape(-1,1) # numpy의 array로 만들어야해서
                 ).toarray()

array([[0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.]])

## LabelBinarizer : OneHotEncoding을 대신 할 수 있다

In [31]:
from sklearn.preprocessing import LabelBinarizer

In [32]:
lb = LabelBinarizer()
lb.fit_transform(df.pName) # 동일한 결과를 얻을 수 있다

array([[0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0]])

In [33]:
# pandas의 get_dummies의 함수에서도 가능!!
# sklearn보다 이게 훨씬 편하겠네
pd.get_dummies(df)

   price  pName_TV  pName_공기청정기  pName_냉장고  pName_노트북  pName_에어컨
0    100         0            0          1          0          0
1     80         1            0          0          0          0
2    150         0            0          0          0          1
3    100         0            0          1          0          0
4     50         0            0          0          1          0
5     40         0            1          0          0          0

# 데이터 스케일링

## StandardScaler

In [35]:
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

In [37]:
iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [38]:
iris_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [40]:
scaler = StandardScaler()
iris_scaled = scaler.fit_transform(iris_df)
iris_scaled_df = pd.DataFrame(iris_scaled,columns=iris.feature_names)
iris_scaled_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
5            -0.537178          1.939791          -1.169714         -1.052180
6            -1.506521          0.788808          -1.340227         -1.183812
7            -1.021849          0.788808          -1.283389         -1.315444
8            -1.748856         -0.362176          -1.340227         -1.315444
9            -1.143017          0.098217          -1.283389         -1.447076
10           -0.537178          1.479398          -1.283389         -1.315444
11           -1.264185          0.788808          -1.226552         -1.315444
12           -1.264185         -0.131979          -1.340227         -1.447076
13           -1.870024         -0.131979          -1.510739         -1.447076
14           -0.052506          2.169988          -1.453901         -1.315444
15           -0.173674          3.090775          -1.283389         -1.052180
16           -0.537178          1.939791          -1.397064         -1.052180
17           -0.900681          1.019004          -1.340227         -1.183812
18           -0.173674          1.709595          -1.169714         -1.183812
19           -0.900681          1.709595          -1.283389         -1.183812
20           -0.537178          0.788808          -1.169714         -1.315444
21           -0.900681          1.479398          -1.283389         -1.052180
22           -1.506521          1.249201          -1.567576         -1.315444
23           -0.900681          0.558611          -1.169714         -0.920548
24           -1.264185          0.788808          -1.056039         -1.315444
25           -1.021849         -0.131979          -1.226552         -1.315444
26           -1.021849          0.788808          -1.226552         -1.052180
27           -0.779513          1.019004          -1.283389         -1.315444
28           -0.779513          0.788808          -1.340227         -1.315444
29           -1.385353          0.328414          -1.226552         -1.315444
..                 ...               ...                ...               ...
120           1.280340          0.328414           1.103783          1.448832
121          -0.294842         -0.592373           0.649083          1.053935
122           2.249683         -0.592373           1.672157          1.053935
123           0.553333         -0.822570           0.649083          0.790671
124           1.038005          0.558611           1.103783          1.185567
125           1.643844          0.328414           1.274295          0.790671
126           0.432165         -0.592373           0.592246          0.790671
127           0.310998         -0.131979           0.649083          0.790671
128           0.674501         -0.592373           1.046945          1.185567
129           1.643844         -0.131979           1.160620          0.527406
130           1.886180         -0.592373           1.331133          0.922303
131           2.492019          1.709595           1.501645          1.053935
132           0.674501         -0.592373           1.046945          1.317199
133           0.553333         -0.592373           0.762758          0.395774
134           0.310998         -1.052767           1.046945          0.264142
135           2.249683         -0.131979           1.331133          1.448832
136           0.553333          0.788808           1.046945          1.580464
137           0.674501          0.098217           0.990108          0.790671
138           0.189830         -0.131979           0.592246          0.790671
139           1.280340          0.098217           0.933271          1.185567
140           1.038005          0.098217           1.046945          1.580464
141           1.280340          0.098217           0.762758          1.448832
142          -0.052506         -0.822570           0.762758          0.922303
143           1.159173          0.328414           1.217458          1.448832
144           1.038005          0.558611           1.103783          1.712096
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [41]:
iris_scaled_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02
mean,-1.690315e-15,-1.842970e-15,-1.698641e-15,-1.409243e-15
std,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00
min,-1.870024e+00,-2.433947e+00,-1.567576e+00,-1.447076e+00
25%,-9.006812e-01,-5.923730e-01,-1.226552e+00,-1.183812e+00
50%,-5.250608e-02,-1.319795e-01,3.364776e-01,1.325097e-01
75%,6.745011e-01,5.586108e-01,7.627583e-01,7.906707e-01
max,2.492019e+00,3.090775e+00,1.785832e+00,1.712096e+00

## MinMaxScaler
- 데이터를 0과 1 사이의 값으로 변환 (음수가 있으면 -1과 1 사이의 값으로 변환)

In [43]:
from sklearn.preprocessing import MinMaxScaler

In [46]:
mms = MinMaxScaler()
iris_scaled2 = mms.fit_transform(iris_df)
iris_scaled2_df = pd.DataFrame(iris_scaled2,columns=iris.feature_names)
iris_scaled2_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
5             0.305556          0.791667           0.118644          0.125000
6             0.083333          0.583333           0.067797          0.083333
7             0.194444          0.583333           0.084746          0.041667
8             0.027778          0.375000           0.067797          0.041667
9             0.166667          0.458333           0.084746          0.000000
10            0.305556          0.708333           0.084746          0.041667
11            0.138889          0.583333           0.101695          0.041667
12            0.138889          0.416667           0.067797          0.000000
13            0.000000          0.416667           0.016949          0.000000
14            0.416667          0.833333           0.033898          0.041667
15            0.388889          1.000000           0.084746          0.125000
16            0.305556          0.791667           0.050847          0.125000
17            0.222222          0.625000           0.067797          0.083333
18            0.388889          0.750000           0.118644          0.083333
19            0.222222          0.750000           0.084746          0.083333
20            0.305556          0.583333           0.118644          0.041667
21            0.222222          0.708333           0.084746          0.125000
22            0.083333          0.666667           0.000000          0.041667
23            0.222222          0.541667           0.118644          0.166667
24            0.138889          0.583333           0.152542          0.041667
25            0.194444          0.416667           0.101695          0.041667
26            0.194444          0.583333           0.101695          0.125000
27            0.250000          0.625000           0.084746          0.041667
28            0.250000          0.583333           0.067797          0.041667
29            0.111111          0.500000           0.101695          0.041667
..                 ...               ...                ...               ...
120           0.722222          0.500000           0.796610          0.916667
121           0.361111          0.333333           0.661017          0.791667
122           0.944444          0.333333           0.966102          0.791667
123           0.555556          0.291667           0.661017          0.708333
124           0.666667          0.541667           0.796610          0.833333
125           0.805556          0.500000           0.847458          0.708333
126           0.527778          0.333333           0.644068          0.708333
127           0.500000          0.416667           0.661017          0.708333
128           0.583333          0.333333           0.779661          0.833333
129           0.805556          0.416667           0.813559          0.625000
130           0.861111          0.333333           0.864407          0.750000
131           1.000000          0.750000           0.915254          0.791667
132           0.583333          0.333333           0.779661          0.875000
133           0.555556          0.333333           0.694915          0.583333
134           0.500000          0.250000           0.779661          0.541667
135           0.944444          0.416667           0.864407          0.916667
136           0.555556          0.583333           0.779661          0.958333
137           0.583333          0.458333           0.762712          0.708333
138           0.472222          0.416667           0.644068          0.708333
139           0.722222          0.458333           0.745763          0.833333
140           0.666667          0.458333           0.779661          0.958333
141           0.722222          0.458333           0.694915          0.916667
142           0.416667          0.291667           0.694915          0.750000
143           0.694444          0.500000           0.830508          0.916667
144           0.666667          0.541667           0.796610          1.000000
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]